name: CRetor_Analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  - jupyter
  - ipykernel
  - pip
  - pip:
      - sentence-transformers
